name: .NET Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH_CONSUMER: './Stanmore.Consumer'
  AZURE_FUNCTIONAPP_PACKAGE_PATH_DISTRIBUTOR: './Stanmore.Distributor'
  DOTNET_VERSION: '10.0.x' # set this to the dotnet version to use

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build & Publish API
        run: dotnet publish ./Stanmore.API/Stanmore.API.csproj -c Release -o ./output/API

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stanmore.API
          path: ./output/API

  build-and-deploy-consumer:
    name: Build Consumer
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_CONSUMER }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure for Neasden.Consumer
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D1048696EB3546ABBCD3B60359C478FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_78182D5F585341AFA90E8B6771E774C6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DC4C841F3A4D435293D83BD6B4B02BE6 }}
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'stanmore-consumer-ping'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_CONSUMER }}/output'

  build-and-deploy-distributor:
    name: Build Distributor
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_DISTRIBUTOR }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure for Neasden.Distributor
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_222BB1691E8548D2BAF3D82B08832820 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DEA147B0F8AE47B0A737CBB0E5EFE1F7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A856CF0266B24170977379BBAAA52931 }}
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'stanmore-distributor-ping'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_DISTRIBUTOR }}/output'



  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [ build-api ]
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Stanmore.API artifact
        uses: actions/download-artifact@v4
        with:
          name: Stanmore.API
          path: ./output/API
      
      - name: Login to Azure for Stanmore.API
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B93B4755420427386759BDA97746958 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5AD04CCE4FE44D4D96AB1F382332E518 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D66344F3F5C41A98FD9B04225886D28 }}

      - name: Deploy Stanmore.API
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stanmore'
          slot-name: 'Production'
          package: ./output/API